### ISSUE TITLE
Finding 'dmt-deploy' Operations

### ISSUE THREAD

**Issue by a6b8** [Trac-Systems/tap-reader#28]
I'm currently trying to find the following deployment via the API:

```json
{
  "p": "tap",
  "op": "dmt-deploy",
  "elem": "af328dc8cb5955c7f9e3db10ce3bd295f8e6974a7c7af456d1beefb702b04c33i0",
  "tick": "natcats",
  "dt": "h"
}
```

InscriptionID: 3e09b19d668e39bfa16aeae7882c123bfc42f939a09426b240b176f98628f487i0

The element is retrievable via `getDmtElementsList`. However, how can I search for "dmt-deploy" operations?

**Comment by TracSystems** [comment]
There will be an update in the next couple of days that addresses this, so you will be available to find these

**Comment by a6b8** [comment]
awesome!

**Comment by elix1er** [comment]
@a6b8 check the newest release and docs
