### ISSUE TITLE
REST API returns empty strings instead of null

### ISSUE THREAD

**Issue by TracSystems** [Trac-Systems/tap-reader#30]
This API call for example will return empty strings instead of null values for "transferable" properties, while it does so when calling the underlying function natively:

http://localhost:5099/getHolders/dmt-nat?offset=111&max=111

This problems seems to be across the REST API. Instead, all REST return values must match of those defined in TracManager.mjs

**Comment by elix1er** [comment]
fixed on commit at:
 
https://github.com/Trac-Systems/tap-reader/commit/cfb6504b072e3f1c132934481c5e0d306475b717#diff-3ddd7ca541f45f3d07408c1f0e61b3150799f3f51b9ba126f0374b1085917bbeR651-R656
