### ISSUE TITLE
Endpoint for getDMTMintWallet with ticker

### ISSUE THREAD

**Issue by LRam10** [Trac-Systems/tap-reader#37]
Adding an endpoint to get mints for an address and ticker, similar to the `getAccountMintList/:address/:ticker`. 
Currently `getDmtMintWalletHistoricList(address, offset, max)` return all mints, making hard to order them by a specific ticker.

**Comment by TracSystems** [comment]
added to todo

**Comment by LRam10** [comment]
@TracSystems 
Im building a DMT app , as new elements are been registered, users would like search a specific element. I believe a  `getDmtElements(name)` endpoint would also be helpful.

Thanks for all the work on supporting DMT!

**Comment by TracSystems** [comment]
fixed in 0.14 beta

**Comment by TracSystems** [comment]
fixed in 0.14 beta

**Comment by TracSystems** [comment]
fixed in 0.14 beta
